### ISSUE TITLE
GitHub Actions自动部署成功但是页面空白没有内容

### ISSUE THREAD

**Issue by YconquestY** [chen-junyi/article#1]
你好，我在用GitHub Actions部署VuePress网页。部署成功后github.io链接访问正常，不会报错404，但是所有build的页面都是空白页，显示不出任何内容。请问你是否知道原因呢？

**Comment by process1024** [comment]
> 你好，我在用GitHub Actions部署VuePress网页。部署成功后github.io链接访问正常，不会报错404，但是所有build的页面都是空白页，显示不出任何内容。请问你是否知道原因呢？

看了下， 你部署后的页面有js报错，本地build后看看什么错，排查一下吧，这两天我把项目切到vitepress了，有兴趣也可以看下

**Comment by YconquestY** [comment]
谢谢。
